### PR TITLE
Fix spelling error 

### PR DESCRIPTION
**Pull request by naton**
Hope I did this the intended way, first commit in this repo..

### CODE REVIEW

**Comment by gvilarino** [comment]
Thanks @naton !

Would you kindly update your commit message for 9993f65? Just do a `git commit --amend` ([more info here](http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git)). That would make your PR fit for merging.

If you're up to it, please read [this article about git conventions](https://medium.com/code-adventures/git-conventions-a940ee20862d) and try to abide to them in future contributions.

**Comment by naton** [comment]
Sorry, you lost me there. I only know how to use Atlasssian SourceTree and the "amend last commit" option doesn't seem to fix what you want me to (since I've done a commit afterwards too, and it only seem to affect the last commit).

**Comment by gvilarino** [comment]
@naton do it with the `git` command in your terminal; [here's how to](http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git)

Also, I'd recommend you ditch any GUI tools for using git; you're usually losing over 70% of its power

**Comment by slifszyc** [comment]
Merged in 919f892051360d265b8efb46ddb1598b05661798

**Pull request closed without merging**
