### PR TITLE
Galician translation

### PR DESCRIPTION
**Pull request by dalareo**
Included Galician locale. Added translation.

### CODE REVIEW

**Comment by gvilarino** [comment]
You're missing some translations. For instance:

screen shot 2015-01-16 at 8 28 26 am

Do a side-by-side comparison with `en.json` and please add whatever's missing. `en.json` is always the complete language reference.

**Comment by gvilarino** [comment]
And, please, keep your commit comments in english; I won't accept non-english PRs

**Comment by diegomestizo** [comment]
I think all missing translations are done, now. Please confirm

**Comment by gvilarino** [comment]
I took the liberty of fixing some missing translation keys as well as the file indentation; it now looks great. Thanks @dalareo and @diegomestizo for this :)

**Comment by gvilarino** [comment]
@dalareo and @diegomestizo, I also added you to [our contributors file](https://github.com/DemocracyOS/app/blob/development/CONTRIBUTORS.md)

Thanks again!

**Comment by gvilarino** [comment]
By the way @dalareo & @diegomestizo , if you'd like to, you can also do the (very small) Galician translation on [notifier](https://github.com/DemocracyOS/notifier) so you also get emails in Galician :D

**Comment by dalareo** [comment]
We've created a pull request on notifier!

**Comment by diegomestizo** [comment]
Thank you, @gvilarino!

**Pull request merged**
