### PR TITLE
Add Smooth scrolling

### PR DESCRIPTION
**Pull request by solde9**
Ok, I went ahead and forked component/scroll-to, then changed the scroll functionality for comments and comment-replies. I hope everything it's ok.
What remains to be done is checking if the elements are off-screen to perform the action. I'll see if I can find something for that, but at least the scroll is working.

#659

### CODE REVIEW

**Comment by gvilarino** [comment]
Thanks! Let's have @slifszyc have a look at this and merge if approved

**Comment by slifszyc** [comment]
I'll take a look at it in a couple of hours.

Thanks @solde9 !

**Comment by solde9** [comment]
I've added a condition for scrolling only when the elements are partially off-screen.

**Comment by solde9** [comment]
What's wrong?

**Comment by slifszyc** [comment]
We are deprecating `component(1)` on our next release of version `1.0.0` of DemocracyOS, in which we are currently working.

Please update this PR to point to `1.0.0` and test again the changes you've made for it to be merged.

**Comment by solde9** [comment]
I'll take a look! Thanks!

**Comment by solde9** [comment]
I rebased the branch on top of development and tested the app. I also added the scroll to edit-comments. Is there anything else that needs to be done?

**Comment by solde9** [comment]
I made a few changes from the original implementation, in which the partially-hidden element was being scroll all the way up to the top. Now instead of that, I just scroll until the element is on-screen. I also wrapped the common functionality to a local component.

**Comment by gvilarino** [comment]
wow, thanks!

**Pull request merged**
