### PR TITLE
rename LICENSE.txt to LICENSE.md

### PR DESCRIPTION
**Pull request by a0viedo**
In order to folow GitHub and npm conventions.

### CODE REVIEW

**Comment by gvilarino** [comment]
I believe I read some conventions about having a `LICENSE.txt` or just plain `LICENSE` text file; not quite it being a `markdown` file. Can you provide a link to a description of these conventions you mention?

**Comment by mjlescano** [comment]
All are good options: https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository

**Comment by a0viedo** [comment]
well, for what it's worth, GitHub is not rendering files with txt extension that contains markdown

**Comment by gvilarino** [comment]
I just removed the markdown and updated the year. We'll be revising this completely before launching `1.0.0`

**Pull request closed without merging**
