### PR TITLE
added uk.json support

### PR DESCRIPTION
**Pull request by tarasdudar**
I've added uk.json and templates for other languages already supported by locale for time stamps. I've also included the new languages into index.js and component.json in the translations library and added cyrillic alphabet into regexp. It's only cyrillic for now. I have not had a chance to look into supporting other languages for regexp yet. I've also added some README.dm files. I've compiled it and verified that it works. I'll work on ru,json next.

### CODE REVIEW

**Comment by gvilarino** [comment]
@tarasdudar thanks for the PR. While I apprecieate the effor of building every template; this is not the approach we have in DemocracyOS for languages.

Please remove all non-fully supported languages from your PR and also the `README.md` on pretty time prints from the PR. If you think an explanation is due for that; add a Localization page to the wiki explaining how our localization is independent from the time print localization because of the dependencies we use.

Do this and I'll merge the PR.

Thanks again,
G.-

**Comment by tarasdudar** [comment]
Thanks @gvilarino,

Done. I was not sure how github pull requst system works in cases like that. So I've repeated the steps I did yesterday and looks like it has created a second pull request with all the deletions I've done. It might be easier for you to review if I just cancel my original request and submit the new one. Just let me know if this the case and I'll do that.

**Comment by gvilarino** [comment]
@tarasdudar thanks, merged. I did some minor fixes (see them here 803e58bd2e9e11f971216d173fec57fd51a031f3) so code fits our conventions.

The way you should work with PRs is considering them a conversation/code review about an upgrade. Whenever you push code to the branch you opened the PR from, the PR gets updated, so it's all on the same page.

For further reading, I'd recommend [this official doc about PRs](https://help.github.com/articles/using-pull-requests/) or even [github-flow](http://githubflow.github.io/); which is how Github itself works internally with PRs.

Thanks again for your contribution.

**Comment by tarasdudar** [comment]
Thanks @gvilarino,

Your fixes make sense. I should have done it that way to begine with.

**Pull request merged**
