### PR TITLE
Fix When posting a new comment, timestamp doesn't show immediately

### LINKED ISSUE #619: When posting a new comment, timestamp doesn't show immediately
When posting a new comment, there is a delay for this label to appear:
image

That's because of #615: the `timeago` polling is longer. We should force to update when posting a new comment.

### PR DESCRIPTION
**Pull request by solde9**
Fix #619

### CODE REVIEW

**Comment by jfresco** [comment]
Good work @solde9. Thank you.

**Comment by solde9** [comment]
Thanks!
I just realized that `addmycomment ` is called too on page load for each comment. I hope this wouldn't be a problem in a page with lots of comments.

**Comment by jfresco** [comment]
That's true. I made some improvements on [this branch](https://github.com/DemocracyOS/app/compare/fix/improve-comments-timestamp). Please tell me your opinions.

**Comment by solde9** [comment]
Ohh that's much better! Thank you!

**Pull request closed without merging**
