### PR TITLE
Added Japanese translation from Mair

### PR DESCRIPTION
**Pull request by ben-pr-p**
I added and tested the Japanese translation. The following things are still missing from jp.json that are in en.json:

```
{
  "admin-laws-form.alert.no-tags": "No tags were found, please <a href=\"/admin/tags/create\">create one</a> before start creating topics",
  "admin-laws-form.label.resources": "Resources",
  "admin-laws.list.add-topic": "New",
  "admin-laws.list.close.future": "Closing",
  "admin-laws.list.search.placeholder": "Search a topic...",
  "admin-laws.list.sort": "Sort",
  "admin-sidebar.whitelists.title": "Enabled users",
  "admin-tags.list.add-tag": "New",
  "admin-tags.list.search.placeholder": "Search a tag...",
  "admin-whitelist.actions": "Actions",
  "admin-whitelist.delete-whitelist.confirmation.body": "This action will erase data permanently. Would you like to proceed?",
  "admin-whitelist.delete-whitelist.confirmation.ok": "Delete",
  "admin-whitelist.delete-whitelist.confirmation.title": "Delete rule",
  "admin-whitelist.type": "Type",
  "admin-whitelist.value": "Value",
  "admin-whitelists-form.button.delete": "Delete",
  "admin-whitelists-form.message.onsuccess": "Whitelist successfully saved",
  "admin-whitelists-form.value.placeholder": "Comma separated emails or just one email",
  "admin-whitelists.list.add-whitelist": "Add",
  "admin-whitelists.list.search.placeholder": "Search a whitelist...",
  "browser-update.ie-old-version-warning": "You are using an usuported version of Internet Explorer.",
  "browser-update.in-order-warning": "In order to use DemocracyOS, please update your browser.",
  "browser-update.switch-to": "Switch to ",
  "browser-update.update-your": "Update your ",
  "browser-update.why": "Why?",
  "browser-update.why.newer-browsers": "Newer browsers take advantages of the newest technologies and ensure safer browsing experiences.",
  "browser-update.woops": "Whoops.",
  "comment-card.not-spam": "Not Spam",
  "comment-card.report-spam": "Report as spam",
  "comments.removed": "The argument was removed",
  "comments.removing-argument": "You are removing this argument as a staff member",
  "comments.score.not-allowed": "You're not allowed to qualify your own argument",
  "common.close": "Closes",
  "common.no-user-for-email": "No user found for that email address",
  "common.read-more": "Read more",
  "forgot.error.email-not-valid": "You must validate your email address before you can reset your account password",
  "header.admin": "Manage",
  "homepage.create-debate": "Create my first topic",
  "homepage.no-laws": "There are no topics to display",
  "notifications.error.connection-refused": "Unable to connect to notifications engine",
  "password.retype": "Retype new password",
  "proposal-article.participant.plural": "Participants",
  "proposal-options.error.voting": "An error occurred while processing your vote. Please try again",
  "proposal-options.must-be-signed-in": "You must be signed in to vote on this topic",
  "resend-validation-email-form.error.email-not-valid.no-link": "The email address for this citizen is not validated. We send citizens a welcome email when they sign up. Please check your email (remember to check your spam folder too) and click on the link supplied on the email.",
  "settings-notifications.no": "No",
  "settings.notificatinos.get-email-when": "Get an email when",
  "settings.notifications.new-topic": "A new topic gets published",
  "settings.notifications.title": "Notifications settings",
  "settings.notificatoins.someone-replies-your-comments": "Someone replies one of your comments",
  "settings.title": "Settings",
  "signin.account-disabled": "This account has been disabled",
  "signin.error.email-not-valid": "The email address for this citizen is not validated. We send citizens a welcome email when they sign up. Please check your email (remember to check your spam folder too) and click on the link supplied on the email. Click <a href='/signup/resend-validation-email'>here</a> if you need the welcome email to be resent",
  "signin.login": "Login",
  "signin.signup": "Signup",
  "signup.accepting": "By signing up you are accepting our",
  "signup.now-can-vote": "You can now argue and vote on bills!",
  "signup.user-already-validated": "This citizen already validated the email address",
  "signup.whitelist.email": "Email {email} is not allowed by admin",
  "validators.max-length.plural": "It must be at least {n} characters long at most",
  "validators.max-length.singular": "It must be 1 character long at most"
}
```

Maybe they can be pieced together from the other translations, but I'm not confident in my ability to distinguish Japanese word boundaries.

### CODE REVIEW

**Comment by Shakyamuni177te** [comment]
This is an important revision and might make it worth using the DemocracyOS codebase for the UK version. Well, sort of. It would be nice it if worked 'out of the box'. A lot of our collaborators have had troubles.

**Comment by mjlescano** [comment]
Thanks @ben-pr-p! but for now we can't merge a language with so many missing keys.

**Comment by gvilarino** [comment]
@ben-pr-p is there any reason why you're not using plain japanese characters? I mean, supposedly `UTF-8` supports them, doesn't it?

**Comment by ben-pr-p** [comment]
@gvilarino The encoding got messed up when I used a Python program to format it - most recent commit fixes that.

@mjlescano No worries! Will add the rest when I get them from Mair.

**Comment by gvilarino** [comment]
@ben-pr-p cool! One more thing: could you please squash your commits into just one? That'd make the PR merge-ready (once you've added the missing keys, of course).

**Pull request closed without merging**
