### PR TITLE
Normalize email address on sign[up/in] workflows

### LINKED ISSUE #689: Allow login not beign case-sensitive on the email
captura de pantalla 2015-03-05 a las 17 41 52

### PR DESCRIPTION
**Pull request by jfresco**
When this PR be merged, when a user tries to register with one of this email addresses: `pepe@gmail.com`, `p.e.p.e@gmail.com`, `PEpe@gmail.com`, she will be registered with `pepe@gmail.com` (now the app registers the three addresses as three different users). The app will lowercase the email address and strip Gmail alias tricky characters.
The `forgot` module will have the same behavior.
After this, users previously registered with aliases or caps will become unaccessible.

Closes #689 and #736.

### CODE REVIEW

**Comment by mjlescano** [comment]
* What are we going to do with the apps that already have users with multiple accounts but same gmail email?
* I think it's really weird to discriminate gmail. Is there really a security improvement? Is not sufficient with `lowercase: true` at the model?

**Comment by gvilarino** [comment]
Let's make it configurable. By default it should be disabled but we should allow enforcing of this so official deployments don't *have* to cope with endless accounts per email.

**Comment by gvilarino** [comment]
Also, we may add a 'visible' email field and a 'normalized' email field. Checks would be against the normalized field. This would be required just because `mongo` can't index virtual fields.

**Comment by mjlescano** [comment]
Also, make sure that `STAFF` config emails are beign normalized too.

**Comment by mjlescano** [comment]
We decided to do it with a config

**Comment by gvilarino** [comment]
What's the status here? We need to fix #689

**Comment by mjlescano** [comment]
Will be merged here #905

**Pull request closed without merging**
