### PR TITLE
Don't allow valid users to request resend validation email

### PR DESCRIPTION
**Pull request by mjlescano**
For issue #604

### CODE REVIEW

**Comment by mjlescano** [comment]
@gvilarino, @jfresco, have some questions regarding translations:

The new error message is only to be shown on signup process, is it ok to be at the "common." namespace?
How about the other languages? I only did the english one, I have to copy in english to the other languages, google translate it, or someone else will take care of it?

**Comment by gvilarino** [comment]
for translations keys we use some sort of tacit criterion: sort of like `module-name.file-or-view-name.string-sort-of-name`, but for some stuff like `or` or `email` that is used all over the place we just fit it under `common.whatever`.

And yes, if you add new keys you should provide translations for all languages based on google translate.

**Comment by jfresco** [comment]
@mjlescano Is this ready for review & merge?

**Comment by gvilarino** [comment]
@jfresco i18n completion still missing

**Comment by mjlescano** [comment]
done!

**Comment by jfresco** [comment]
Good work, thanks.

**Pull request closed without merging**
