### PR TITLE
Wrap localstorage #582

### PR DESCRIPTION
**Pull request by mjlescano**
* Improved lib/store to be able to use localStorage thru https://github.com/marcuswestin/store.js/, also added the possibilty to select fallbacks and order of them (cookies or remote session).

* Implemented on lib/jwt component.

### CODE REVIEW

**Comment by mjlescano** [comment]
#582

**Comment by mjlescano** [comment]
@gvilarino The 'remote' storage is not working, I'm not sure why the assignment of the value on the session is thowing an error. Could you please revise it?

On:
**/lib/store/index.js:14**
`req.session[key] = data;`

**Comment by gvilarino** [comment]
maybe because remote sessions are handled via `JWT`. Some input here @jfresco ?

Also @mjlescano, why do the `store` signatures no longer provide callbacks? Is all the code synchronous? Is that a `store.js` requirement?

**Comment by mjlescano** [comment]
Thanks!

Yes it provides callbacks, but now are optional (needed the synchronous version to be used in jwt.js). The **store.js** doesn't show the signatures, but you can see them in the different storage files, eg **/lib/store/storages/cookie.js**.

**Comment by jfresco** [comment]
I'm getting other error when using `remote` storage:
image
Seems like `require('request')` is not gathering correctly the module thus don't have a `get` method (`require` gets a bare object). Could it be a problem of my build? Anyway, I put the `require` inside the `remote.get` function to continue testing.

Something important: client component `request` requires `jwt`; and `store` requires `request`. When it tries to get the remote token, it crashes because an infinite loop:
image
 
Just a comment: JWT is stateless on server side, it doesn't store session information.

**Comment by mjlescano** [comment]
Closes #582

**Pull request merged**
