### PR TITLE
Added Quill for WYSIWYG text editor

### PR DESCRIPTION
**Pull request by jfresco**
* Added Quill as a dependency
* Created the `richtext` component as a wrapper
* Made textareas in `/admin/laws` form rich text.
* Fixed markup error when showing side comments in `proposal-article` view.

### CODE REVIEW

**Comment by gvilarino** [comment]
Do I have to reset DB for this? My app builds and it starts loading but then I get a blank screen and nothing else.

**Comment by gvilarino** [comment]
Great work. I'm seeing some stuff I'd like updated:

1) Side comments are enabled for blank lines. See the image below:
screen shot 2015-02-13 at 5 48 06 pm

2) I'm seeing a numbered list option but not a bulleted list option. i.e.:
1. I can
2. do
3. this

* But I
* can't do
* this

Also, the edition box is very tall by default. Can we make a big smaller?

**Comment by jfresco** [comment]
Thanks for the findings.

**Comment by jfresco** [comment]
Done @gvilarino. Please tell me if you find something else.

**Comment by gvilarino** [comment]
@jfresco some things I just noticed:

1. When I clink on the "link" icon with no text selected, nothing happens. That's weird. It does work if I select some text before, but it's not clear from the user perspective. Either show a message that you need to select what text to add a link to or do as Gmail does (provides two fields, `text` and `link`, the former being pre-filled if text was selected).

2. When I click on the "image" button I see this:
screen shot 2015-02-18 at 12 30 22 pm
I don't get it, sorry :confused: 

Maybe making the container a bit larger?

**Comment by jfresco** [comment]
1. This is the default behavior of Quill. I can modify this behavior to add the text field and allow showing the popup if no text is selected, but it's a little bit hard work, so I suggest to open a new issue, label it as `enhancement` and defer it.
2. True. Sorry about that. I tried to put a high `z-index` value to the form container but didn't work. I made the whole container a little bit larger (about 330px) to make it fit and it's ok, but now is as large as before (maybe a little less, but still large). Perhaps we can create a new issue to make the popup float outside the Editor.

**Comment by jfresco** [comment]
Video embedding is working with some issues:
- [ ] If more than a video is added to the Editor, the further uses the same `src` than first one.
- [ ] Bad rendering legacy laws with HTML.

**Comment by jfresco** [comment]
Ready to review.
I'm still testing with old laws. I had to touch a lot the `proposal-article` view to leave it backwards-compatible.

**Comment by gvilarino** [comment]
Ignoring this because of #685

**Pull request closed without merging**
