### PR TITLE
[participants] Updated translation keys to fit guidelines. Related to #4...

### PR DESCRIPTION
**Pull request by jfresco**
...06.

### CODE REVIEW

**Comment by gvilarino** [comment]
@jfresco I got a weird behavior here; please confirm if you experience the same:

Prereqs:
* Have 2 user accounts
* Have an admin user (can be any of the previous users)

1. Create a new `law`
2. Navigate to new `law` with user A
3. Vote on that `law` with user A
4. Signout and sign in with user B
5. Vote on that `law` with user B
6. Watch as the participants view repeats a user bubble:

screen shot 2015-01-06 at 8 06 24 pm

**Comment by gvilarino** [comment]
btw I just pushed a new rebase after the release of `0.9.0`

**Comment by jfresco** [comment]
Thanks for finding this @gvilarino. It is now fixed.

**Comment by gvilarino** [comment]
Now looking at it more closely, this seems to not be entirely compliant with the views refactor.

You still have a `swtitchOff` that does nothing but unbindings; you're using `events` and the bindings are set with `bind` instead of `bound`.

Also, the code is using `render`; I'm not entirely sure we're still using this.

@slifszyc I'll assign this to you; it seems you'll be more help than myself.

for checking the errors I mentioned, do a local merge against `development`

**Pull request merged**
