### PR TITLE
Add Vagrant for Development

### PR DESCRIPTION
**Pull request by mjlescano**
### Usage

1. Install [Vagrant](https://www.vagrantup.com/downloads.html)
2. `vagrant up`
3. `vagrant ssh`
4. `cd /vagrant && make`

Ω

### CODE REVIEW

**Comment by mjlescano** [comment]
@gvilarino should I close this and wait for Docker?

**Comment by gvilarino** [comment]
Yeah, I'll close it

**Comment by vladfr** [comment]
Hi @mjlescano I'm interested in picking this up. 

I ran it and make does not work. Seeing lots of warnings with trianglify. The final error is
npm ERR! peerinvalid The package karma-phantomjs-launcher@0.2.1 does not satisfy its siblings' peerDependencies requirements!

**Comment by gvilarino** [comment]
@vladfr we're dropping the `Vagrant` approach in favour of `Docker`

**Pull request closed without merging**
