### PR TITLE
fixed #668, added error handler for incorrect current password

### LINKED ISSUE #668: Change password functionality is not showing any msg when incorrect "Current Password"
If the password on "Current Pasword" is incorrect, and hit "Save", it does't tell you anything.

captura de pantalla 2015-02-24 a las 15 51 39

### PR DESCRIPTION
**Pull request by ben-pr-p**
fixed bug #668 where no error message was displayed if the user typed in an incorrect current password

also found bug in lib/form-view/form-view.js FormView.prototype.response that was parsing a non-JSON error request

### CODE REVIEW

**Comment by gvilarino** [comment]
Awesome! @slifszyc check this out

**Comment by mjlescano** [comment]
Hi @ben-pr-p ! Sorry for the delay merging, looks good. But could you please rebase it with `development`?

**Comment by ben-pr-p** [comment]
So I made a mistake and accidentally added the Japanese commits from the other branch into this one, and then reverted it. Judging by the compare on the pull request, it looks good (no Japanese related changes), but when I try to run it to test it I'm getting an error related to translations/index.js, an illegal token error, and I can't imagine that's an error in the main branch.

Any ideas?

**Comment by mjlescano** [comment]
The PR looks good. Also, there was an error with the response from the `settings-api`, I fixed it directly on `development` [here](https://github.com/DemocracyOS/app/commit/6c8b387ddd9ad2a752653cd879c4f11ffb2b2bb8) and is working ok with your branch. Could you please rebase it again, and if it's working I'll accept the PR.

Couldn't reproduce the translations error. Maybe was the one fixed by [this commit](https://github.com/DemocracyOS/app/commit/8cff9a8b2a4cabac2bae02adf8ac631a66bfa1e5)?

**Comment by jfresco** [comment]
LGTM. I'm going to merge it to `development` and `1.0.0`.

**Pull request merged**
