### PR TITLE
Added new line at end of file

### PR DESCRIPTION
**Pull request by seykron**

### CODE REVIEW

**Comment by fernandezpablo85** [comment]
LGTM

**Comment by seykron** [comment]
Please, merge this PR, it is one of the most important contributions ever made by the community. It was designed by @santisiri, I'm just a simple developer.

**Comment by gvilarino** [comment]
wtf

**Comment by seykron** [comment]
I still think it should be merged, why did you close it without any comment on the code?

**Comment by santisiri** [comment]
<3

**Pull request closed without merging**
