### PR TITLE
Added Traditional Chinese language file.

### PR DESCRIPTION
**Pull request by fabriciodisalvo**
New language file: Traditional Chinese.

### CODE REVIEW

**Comment by gvilarino** [comment]
@fabriciodisalvo the `zh_TW.json` file you're providing isn't in a valid `json` format. You're using invalid characters.

Also you seem to be missing an update on `l10n/supported.js`.

Please test your contribution before PRing; we won't accept broken collaborations.

Also, please update your PR name to something more accurate.

**Comment by fabriciodisalvo** [comment]
Both files updated. PR name changed.
Hope it complies...

**Comment by gvilarino** [comment]
Awesome! You're just missing one little thing: add the `settings.locale.zh_TW` key to `en.json`, `es.json` and `zh_TW.json` to provide a label for the settings language drop-down. If not, this is how it looks:

screen shot 2015-07-01 at 12 46 24 pm

**Comment by fabriciodisalvo** [comment]
Got it. So, should i add that label to every language file?

**Comment by gvilarino** [comment]
Only if you feel confident enough in every language :)




Translations fall back to the english language file so it shouldn't be an issue if it's available in en.json

**Comment by fabriciodisalvo** [comment]
Third time's a charm? I think we are good to go now....

**Comment by fabriciodisalvo** [comment]
An (un)related question:
Shouldnt every  `settings.locale.lang` line refer to every language in that language?
I saw that `en.json` has an entry for  `"Deutsche"` instead of  `"German"` and that made sense...

image

**Comment by gvilarino** [comment]
It's a fairly good point; I guess it's understandable. Keys would still fall back to english if missing in the selected language file.

Would you mind opening an issue for that? I'll label it as a `discussion`.

**Comment by gvilarino** [comment]
@fabriciodisalvo ok, code looks good and works. There's just *one more thing* you need to do. Edit the PR so you submit it to the `development` branch. We don't merge into `master` since only released versions are under `master`

**Comment by fabriciodisalvo** [comment]
Sorry for that, haven't realized... Can I edit this PR or do I need a new one? I'm confused... Thanks in advance.

**Comment by gvilarino** [comment]
Yea; just edit your PR. I can't do it :(

**Pull request closed without merging**
